# Generated by Django 5.1.1 on 2024-10-01 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='queries',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='api.queryexplainer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='upcoming', max_length=10),
        ),
        migrations.AddField(
            model_name='queryexplainer',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_explainer', to='api.appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.CharField(default='', max_length=64),
        ),
    ]
